## Matrix Transpose and Inverse Matrix

Matrix operations are fundamental in linear algebra and are widely used across different scientific and engineering disciplines. In this notebook, we will explore Matrix Transpose and the Inverse Matrix, covering both manual and NumPy-based methods for each.

#### 1. Inverse Matrix

An inverse matrix, denoted as $( A^{-1} )$, is a matrix that, when multiplied by the original matrix $( A )$, results in the identity matrix. The identity matrix has 1s on the diagonal and 0s elsewhere.


$A \times A^{-1} = I$

Where:
- \( A \) is the original matrix
- \( A^{-1} \) is the inverse of the matrix
- \( I \) is the identity matrix (for a 2x2 matrix: \(\begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}\

##### Why Do We Need Inverse Matrices?

Inverse matrices are essential in various fields, including:
- **Solving systems of linear equations**: They help in finding the solutions to a system of linear equations.
- **Transformations in geometry**: Inverse matrices are used in computer graphics to reverse transformations like rotation or scaling.
- **Cryptography**: Many cryptographic algorithms rely on the properties of matrices.
- **Data analysis and machine learning**: Inverse matrices play a role in regression analysis and optimization algorithms.

##### **Finding the Inverse of a 2x2 Matrix Manually**

Given a 2x2 matrix \( A = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \), the formula for the inverse is:

$A^{-1} = \frac{1}{\text{det}(A)} \begin{bmatrix} d & -b \\ -c & a \end{bmatrix}$
Where $( \text{det}(A) = ad - bc )$ is the determinant of matrix \( A \).

Let's start by calculating the inverse of a 2x2 matrix manually.

In [1]:
import numpy as np

# Define matrix A
A = np.array([[1, 2], [3, 4]])

# Calculate determinant manually
a, b = A[0]
c, d = A[1]
det = a * d - b * c
det  # Determinant

# Calculate inverse manually using the formula
if det != 0:
    inverse_manual = np.array([[d / det, -b / det], [-c / det, a / det]])
else:
    inverse_manual = "Matrix is not invertible"
inverse_manual


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Inverse Matrix Using NumPy

NumPy provides a built-in function np.linalg.inv() that computes the inverse of a matrix efficiently.

In [2]:
# Calculate inverse using NumPy
numpy_inverse = np.linalg.inv(A)
numpy_inverse


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

#### 2. Matrix Transpose

A matrix transpose is a new matrix that is formed by swapping the rows and columns of the original matrix. For a matrix \( A = \begin{bmatrix} a & b \\ c & d \end{bmatrix} \), the transpose \( A^T \) is:

$A^T = \begin{bmatrix} a & c \\ b & d \end{bmatrix}$
##### What is Matrix Transpose Used For?

Matrix transposition is frequently used in:
- **Vector space analysis**: It's used to switch between row vectors and column vectors.
- **Computational linear algebra**: It's used to simplify matrix operations in algorithms.
- **Machine learning and data science**: Transposition is used in neural networks and other matrix-heavy algorithms.

##### Manually Calculating the Transpose

To manually calculate the transpose of a matrix, we will create an empty matrix where the rows and columns are swapped.

In [3]:
# Define matrix B
B = np.array([[4, 2], [5, 1]])
B  # Original matrix

# Initialize an empty transpose matrix with swapped dimensions
rows, cols = B.shape
transpose_B = np.zeros((cols, rows))

# Populate transpose matrix
for i in range(rows):
    for j in range(cols):
        transpose_B[j][i] = B[i][j]

transpose_B


array([[4., 5.],
       [2., 1.]])

### Using NumPy’s Built-in Function

NumPy makes the process of transposing a matrix much easier with the .T attribute.

In [4]:
# Using NumPy's built-in transpose function
NumPy_transpose_B = B.T
NumPy_transpose_B


array([[4, 5],
       [2, 1]])

#### Performance Comparison: Manual vs. NumPy Methods

While manual implementations help understand the underlying mechanics, NumPy is much faster and more efficient for large-scale matrix operations. Let's compare the time taken for both methods to transpose a large matrix.

In [5]:
import time

# Generate a large matrix
B_large = np.random.rand(1000, 1000)

# Measure time for manual transpose
start_time = time.time()
transpose_manual = np.zeros((B_large.shape[1], B_large.shape[0]))
for i in range(B_large.shape[0]):
    for j in range(B_large.shape[1]):
        transpose_manual[j][i] = B_large[i][j]
end_time = time.time()
manual_time = end_time - start_time

# Measure time for NumPy transpose
start_time = time.time()
transpose_numpy = B_large.T
end_time = time.time()
numpy_time = end_time - start_time

manual_time, numpy_time


(0.936894416809082, 0.00035500526428222656)

#### Inverse Matrix Applications

Inverse matrices are used in various applications, such as solving systems of linear equations, cryptography, and optimization problems. Here's an example of solving a system of linear equations using the inverse matrix.

Given a system of equations:
$Ax = b$
Where \( A \) is a matrix, \( x \) is a vector of unknowns, and \( b \) is a vector of constants.

The solution can be found by multiplying both sides of the equation by \( A^{-1} \):
$x = A^{-1}b$

In [7]:
# Define matrix A and vector b
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

# Solve for x using the inverse matrix
x = np.dot(np.linalg.inv(A), b)
x


array([-4. ,  4.5])