### NumPy

    NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It offers efficient multidimensional arrays, linear algebra capabilities, and a wealth of mathematical functions.

### Creating Arrays

    From Lists: np.array([1, 2, 3]) converts a Python list into a one-dimensional NumPy array. Similarly, np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) creates a two-dimensional array (matrix).

In [1]:
import numpy as np
# We can create an array by directly converting a list or list of lists:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [2]:
# Create a 2D array (matrix) from a list of lists
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Generating Arrays

    np.arange(start, stop, step): Generates an array with evenly spaced values within a specified range. start (inclusive) and stop (exclusive) define the boundaries. step (optional) controls the increment between elements.
        np.arange(0, 10): [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] (default step of 1)
        np.arange(0, 11, 2): [0, 2, 4, 6, 8, 10] (step of 2)


In [3]:
# Create arrays using np.arange
print(np.arange(0, 10))  # Default step of 1
print(np.arange(0, 11, 2))  # Step of 2

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


### np.zeros(shape)
    Creates an array filled with zeros. shape can be a tuple specifying the dimensions (e.g., (4) for a 1D array with 4 zeros, (5, 5) for a 2D array with 5 rows and 5 columns).


In [4]:
# Generate arrays of zeros 
print(np.zeros(4))
print(np.zeros((5,5)))

[0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### np.ones(shape)
Creates an array filled with ones, similar to np.zeros.

In [5]:
# Generate arrays of ones
print(np.ones(4))
print(np.ones((5,5)))

[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### np.linspace(start, stop, num)
Generates an array with a specified number (num) of evenly spaced values over a given interval (start to stop).

    np.linspace(0, 10, 3): [0.0, 5.0, 10.0] (3 equally spaced values)
    np.linspace(0, 10, 20): More densely spaced values from 0 to 10 (19 elements)

In [6]:
# Generate evenly spaced values
print(np.linspace(0, 10, 3))  # 3 equally spaced values
print(np.linspace(1, 100, 19))  # 20 values


[ 0.  5. 10.]
[  1.    6.5  12.   17.5  23.   28.5  34.   39.5  45.   50.5  56.   61.5
  67.   72.5  78.   83.5  89.   94.5 100. ]


### np.eye(n)
Creates an identity matrix with n rows and columns. The diagonal elements are 1s, and the rest are 0s.

In [7]:
# Creates an identity matrix
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Random Arrays:
#### Uniform Distribution
    np.random.rand(shape):** Generates an array of random floating-point numbers between 0 (inclusive) and 1 (exclusive), uniformly distributed.

In [8]:
# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1].
print(np.random.rand(4))
print(np.random.rand(5,5))

[0.16423008 0.30508756 0.12481829 0.39924077]
[[0.30805088 0.67197216 0.0624615  0.25333656 0.254047  ]
 [0.5110871  0.2505433  0.17559978 0.20215861 0.968798  ]
 [0.98099822 0.96799023 0.03971394 0.37431875 0.48266589]
 [0.80087737 0.55136826 0.10565761 0.23260135 0.09657286]
 [0.78702086 0.19202207 0.3520175  0.10936466 0.78941453]]


#### Random Integers

In [9]:
# Return random integers from low (inclusive) to high (exclusive).
print(np.random.randint(1,100))
print(np.random.randint(1,100,10))

26
[72 93 55  6 35 61 53 90 43 34]


### Indexing and Selection

    Accessing Elements: NumPy indexing is similar to Python lists, but it works with entire arrays at once.

In [10]:
# Numpy Indexing and Selection
#Creating sample array
arr = np.arange(0,11)
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### arr[index]
    Returns the element at the specified index. arr[4] gets the element at index 4 (fifth element).

In [11]:
#Get a value at an index
arr[4]

np.int64(4)

#### arr[start:stop]
    Returns a slice of the array, including elements from start (inclusive) to stop (exclusive). arr[2:5] retrieves elements 2, 3, and 4

In [12]:
#Get values in a range
arr[2:5]

array([2, 3, 4])

In [13]:
#Setting a value with index range (Broadcasting)
arr[4:7]=100
#Show
arr

array([  0,   1,   2,   3, 100, 100, 100,   7,   8,   9,  10])

In [14]:
# Reset array
arr = np.arange(0,11)
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2D Array Indexing:

    arr_2d[row] or arr_2d[row, :]: Selects the entire row at the specified index.
    arr_2d[row, col] or arr_2d[:, col]: Gets the element at the specified row 

In [15]:
# Indexing a 2D array (matrices)
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [17]:
# Getting individual element value
arr_2d[1][0]

np.int64(20)

In [18]:
# other way of Getting individual element value
arr_2d[1,0]

np.int64(20)

### NumPy Operations
NumPy allows you to perform arithmetic operations on arrays element-wise. 
This means that each element in one array is paired with the corresponding element in another array, 
and the operation is applied to these pairs.

#### Element-wise arithmetic

In [19]:
# NumPy Operations
# You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:
arr = np.arange(0,10)
print(arr + arr)
print(arr * arr)
print(arr - arr)
print(arr / arr)# Warning on division by zero, but not an error!
print(arr * 5)
print(arr - 5)
print(arr / 2)
print(1 / arr)# Also warning, but not an error instead infinity


[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0  5 10 15 20 25 30 35 40 45]
[-5 -4 -3 -2 -1  0  1  2  3  4]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/tmp/ipykernel_16558/146362801.py:7: RuntimeWarning: invalid value encountered in divide
  print(arr / arr)# Warning on division by zero, but not an error!
/tmp/ipykernel_16558/146362801.py:11: RuntimeWarning: divide by zero encountered in divide
  print(1 / arr)# Also warning, but not an error instead infinity


#### Exponentials and square roots

In [20]:
print(np.sqrt(arr))
print()
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [21]:
# array to the power 3
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Find max, min, and trigonometric operations


In [22]:
# Find max, min, and trigonometric operations
print(np.max(arr))
print()
print(np.sin(arr))
print()
print(np.log(arr))

9

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/tmp/ipykernel_16558/1973431100.py:6: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


### Matrix Operations

In [23]:
# Matrix Operations in NumPy
# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [24]:
# Matrix multiplication
mult = np.dot(A, B)
print(mult)

[[19 22]
 [43 50]]


In [25]:
# Calculate the inverse
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [26]:
# Solve the linear equation Ax = b
x = np.linalg.solve(A, B)
print(x)

[[-3. -4.]
 [ 4.  5.]]


In [27]:
# Calculate eigenvalues and eigenvectors
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("eigenvalues",eigenvalues)
print("eigenvectors",eigenvectors)

eigenvalues [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
eigenvectors [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Polynomials in NumPy

In [28]:
# Define a polynomial
coefficients = [1, -5, 6]  # Represents the polynomial x^2 - 5x + 6
p = np.poly1d(coefficients)

# Evaluate the polynomial at x = 2
result = p(1)
print(result)

2


In [29]:
# Use np.polyval to evaluate a polynomial at multiple points: 
x_values = np.array([1, 2, 3])
y_values = np.polyval(coefficients, x_values)
print(y_values)

[2 0 0]


In [30]:
# Find the roots of the polynomial
roots = np.roots(coefficients)
print(roots)

[3. 2.]
